### ISSUE TITLE
WebDriverWait Support?

### ISSUE THREAD

**Issue by jezzsantos** [bbaia/protractor-net#13]
I want to wait for certain HTML elements on my page to become enabled, before we can click them. 
They are disabled until certain ajax requests complete, and then they are ready to be clicked.

According to WebDriver there might be a way to do this with WebDriverWait. http://assertselenium.com/2013/01/29/webdriver-wait-commands/

Will you support WebDriverWait?
Or is there another way apart from Thread.Sleep()?

**Comment by bbaia** [comment]
You can do that passing the wrapped WebDriver instance : 
`WebDriverWait wait = new WebDriverWait(ngWebDriver.WrappedDriver, 10);`
