### ISSUE TITLE
Reporter needed for  Protractor for .NET

### ISSUE THREAD

**Issue by SSQE** [bbaia/protractor-net#15]
I'm using Protractor for .NET. Is there any reporter for it? There is a Protractor add-on "Protractor Html Screenshot Reporter". It works on Jasmine framework. Is there a way I can make it work in my protractor-net C# tests? Or is there any reporter available for "Protractor for .NET" that can be used to take screenshot of failed tests and generate HTML report with all test result similar to the way "Protractor Html Screenshot Reporter" does?

**Comment by safrrhmn** [comment]
+1 for this

**Comment by bbaia** [comment]
This should be done for Selenium WebDriver, not specific to Protractor for .NET.

You can already take screenshots easily using the `TakeScreenshot` extension from the WebDriver's Support classes :
```
using OpenQA.Selenium.Support.Extensions;

[Test]
public void ShouldGreetUsingBinding()
{
    var ngDriver = new NgWebDriver(driver);
    ngDriver.Navigate().GoToUrl("http://www.angularjs.org");
    ngDriver.WrappedDriver.TakeScreenshot().SaveAsFile("Step1.jpeg", ImageFormat.Jpeg);
    ngDriver.FindElement(NgBy.Model("yourName")).SendKeys("Julie");
    ngDriver.WrappedDriver.TakeScreenshot().SaveAsFile("Step2.jpeg", ImageFormat.Jpeg);
    Assert.AreEqual("Hello Julie!", ngDriver.FindElement(NgBy.Binding("yourName")).Text);
}
```

Another sample with a screenshot after each test :
```
[TearDown]
public void TearDown()
{
    driver.TakeScreenshot().SaveAsFile(TestContext.CurrentContext.Test.FullName + ".png", ImageFormat.Png);
    driver.Quit();
}
```
