### ISSUE TITLE
When running the test on IE only able to run  the test once

### ISSUE THREAD

**Issue by safrrhmn** [bbaia/protractor-net#16]
This is pretty similar to http://stackoverflow.com/questions/21382962/when-running-protractor-with-phantomjs-browser-only-able-to-run-tests-once. Only one of my tests run on IE and after that all breaks. This issue is not reproducible on Firefox or Chrome

See here for detail.
http://stackoverflow.com/questions/28245166/protractor-and-ie11-navigation-issue

**Comment by safrrhmn** [comment]
Accidentally closed

**Comment by safrrhmn** [comment]
@bbaia Have you considered looking at this?

**Comment by bbaia** [comment]
Yes, I'm working on it but I can't even run one test on IE after updating to version 11.
Investigating...

**Comment by safrrhmn** [comment]
Thanks for your time. I was actually able to run some tests on IE11

**Comment by bbaia** [comment]
Which NuGet package for IE driver are you using ?

**Comment by safrrhmn** [comment]
https://github.com/SeriousM/WebDriver.IEDriverServer-nuget

And, Just heads up there is a known issue with windows update for IE11. I did not take that update. See https://connect.microsoft.com/IE/feedback/details/1062093/installation-of-kb3025390-breaks-out-of-process-javascript-execution-in-ie11
