### ISSUE TITLE
NgBy class don't have 'Model' attribute to find elements

### ISSUE THREAD

**Issue by patro1985** [bbaia/protractor-net#20]
I tried to identify elements with ng-model attribute, 
it throws error: 'protractor.NgBy' does not contain a definition for 'Model', please help! 
[attached screenshot] - Visual studio 2012 express edition
![untitled](https://cloud.githubusercontent.com/assets/8268506/6992257/3de6c6a4-dae1-11e4-969e-83e6765591d8.png)

**Comment by safrrhmn** [comment]
You need to pass the rootElement of the page which is most of the time ng-app attribute as a second argument while instantiating the NgWebDriver

**Comment by safrrhmn** [comment]
@bbaia  I see the changes on source files but last merge never made into NuGet package

**Comment by bbaia** [comment]
Yeah, I forgot to update the package after merging  #19...
Now it's done, I just pushed new version (0.5.0) of `Protractor` NuGet package

**Comment by patro1985** [comment]
Can you please provide a sample code of passing the argument as you
mentioned, reason is I am quite new to this protractor for net, Thank you

On Saturday, April 4, 2015, Saifur <notifications@github.com> wrote:

> You need to pass the rootElement of the page which is most of the time
> ng-app attribute as a second argument while instantiating the NgWebDriver
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbaia/protractor-net/issues/20#issuecomment-89578312>.
>


-- 
THANKS&REGARDS
SUNIL PATRO
7893903025

**Comment by safrrhmn** [comment]
@patro1985 I misunderstood your question. @bbaia Now the NuGet package is updated pull the new version

**Comment by safrrhmn** [comment]
@bbaia Thank you sir! Appreciate your hard work

**Comment by patro1985** [comment]
Getting following error with the new version of protractor(0.5.0), (Just trying to launch the browser with ngwebdriver) -

![image](https://cloud.githubusercontent.com/assets/8268506/7003714/d3858532-dc7c-11e4-898f-6d6e59bb2f40.png)

![image](https://cloud.githubusercontent.com/assets/8268506/7003706/a9f1caa0-dc7c-11e4-8f9c-563550d33915.png)
