### ISSUE TITLE
Refreshing error

### ISSUE THREAD

**Issue by Meir017** [bbaia/protractor-net#21]
When refreshing it the driver doesn't wait for angular and therefore it can cause error when clicking on save buttons etc...
The function refresh should call the WaitForAngular method before refreshing
````csharp
public void Refresh()
        {
            this.ngDriver.WaitForAngular();
            this.navigation.Refresh();
        }
````

**Comment by bbaia** [comment]
You're right.
Same goes for INavigation.Forward() and INavigation.Back() methods
