### ISSUE TITLE
Getting a Pull request merged with Parent Branch

### ISSUE THREAD

**Issue by JP-3** [bbaia/protractor-net#24]
I’ve never done a pull request before so I’m wondering if I did something wrong or if there is another reason why my request isn’t being merged into the parent branch of code?  I see a lot of NgBy methods have been rendered obsolete by the Model method, the problem I have is some elements that don’t have that tag available such as button and label. So I added them and was hoping to get them into the next NuGet package so I can use them if possible.

**Comment by bbaia** [comment]
You did well. I was just thinking about it.
