### ISSUE TITLE
Closed Pull Request Question "Added Find By ButtonText, ButtonTextPartial, LabelText"

### ISSUE THREAD

**Issue by JP-3** [bbaia/protractor-net#29]
OK, i'm going to get back into this stuff this week I think so I decided to look back at what I was doing. I can see the Button is angular as it has the ng.click but rather then spying to see what the properties were I found it easier to just look for the text of the button as I can just read it off the page and for the Label you can see both the angular models are identical for both labels, except for the label itself.  Can you let me know what your thoughts are if you have a minute.  Thanks Bruno  

<button class="btn btn-primary" ng-click="SearchController.search()">
                               “Search”
<label type="button" class="btn btn-default ng-pristine ng-valid active" ng-model=" SearchController.toggleOption" btn-radio="'not_linked'">Not Linked</label>

<label type="button" class="btn btn-default ng-pristine ng-valid" ng-model="SearchController.toggleOption" btn-radio="'linked'">Linked</label>

**Comment by bbaia** [comment]
#22
