### ISSUE TITLE
ngDriver.FindElement should return null if nothing is found, not throw error

### ISSUE THREAD

**Issue by gligoran** [bbaia/protractor-net#34]
At the moment, if ```ngDriver.FindElement``` doesn't find anything, it throws an error. This means that using it in ```Assert``` statements is impossible. It would be really nice if one could do thing like this:

```csharp
Assert.IsNotNull(ngDriver.FindElement(NgBy.Model("myModel")));
```

**Comment by Meir017** [comment]
I think it should be like in the RemoteWebDriver and throw a NoSuchElement exception

**Comment by bbaia** [comment]
As @Meir017 said, it should have the same behavior than the Selenium WebDriver Framework
