### ISSUE TITLE
No support for non-Angular pages

### ISSUE THREAD

**Issue by DKroot** [bbaia/protractor-net#36]
* Some applications might be a mix of Angular and traditional server-generated pages
* Even when your application is 100% Angular, your infrastructure might present a non-Angular page, for example a login page.

Currently,  `Driver.Navigate().GoToUrl(url)` unconditionally throws an exception when presented with non-Angular page. This request is to support this situation somehow.

The only way I could think of to deal with this in my code is with somewhat ugly, swallowing exception code:

```
try
{
    Driver.Navigate().GoToUrl(url);
}
catch (InvalidOperationException e)
{
    // Ignore "Angular could not be found on the page" Protractor exception
    Log.DebugFormat("Ignoring exception in navigation to {0}: {1}", url, e.Message);
}
```

And this is done in my general navigation routine that navigates to all pages.

My first thought was to do this: `((NgWebDriver) Driver).WrappedDriver.Navigate().GoToUrl(url)`, but this would completely bypass Protractor code that initializes pages after login. I can't just go and login either because login page is presented transparently to the application-under-test once per session.

**Comment by bbaia** [comment]
Use the new GoToUrl(url, ensureAngularApp) method available in v0.7.0 :
```
ngDriver.Navigate().GoToUrl(url, false);
```
