### ISSUE TITLE
NgBy.Bindings() doesn't work with $compileProvider.debugInfoEnabled(false);

### ISSUE THREAD

**Issue by MaximeSangoi** [bbaia/protractor-net#40]
Hi bbaia,

I have few problems with NgBy.Bindings(). Here is the line that cause me headache : 
`ngDriver.FindElement(NgBy.Binding("::$ctrl.test"))`.

It seems NgBy.Bindings() needs the debug info that Angular provides by default. If you deactivate the Angular debug with
`$compileProvider.debugInfoEnabled(false);`
NgBy.Bindings() method doesn't work and can't find the element.

Could you please provide a solution as soon as possible, or I will be forced to deactivate End-to-End tests on my beloved project.

Regards,

**Comment by julienmartin** [comment]
:+1:

**Comment by bbaia** [comment]
Related to #60

**Comment by MaximeSangoi** [comment]
Alright, thanks for your time !

**Comment by bbaia** [comment]
Available in v0.9.2
