### ISSUE TITLE
Do we support Selenium 3.0 beta 2 - Firefox 47+ with Geckodriver ?

### ISSUE THREAD

**Issue by iPiyushPatel** [bbaia/protractor-net#45]
Hi,
I've just updated Selenium version to 3.0 beta 2 , also downloaded required geckodriver (https://github.com/mozilla/geckodriver/releases) , and started testing with Firefox 47.0.1.

I noticed that - driver doesn't wait for angular request to finish & test fails.  Can you please help ?
Let me know if any other additional info required.

**Comment by yabols** [comment]
I have same problem, I thought that this was problem with our page since we are developing new product   but after debugging source code I find out that this is only problem with firefox(my version is 48.0.2) and geckodriver.

**Comment by iPiyushPatel** [comment]
Hi there, 
Is there any update on this ? This is blocking issue for moving to Selenium 3.0

I've also raised on Geckodriver forum & they say - it is not from there end. It should be from Protractor-net end. SEE: https://github.com/mozilla/geckodriver/issues/208

Please advice.

**Comment by iPiyushPatel** [comment]
hey @bbaia - can you please review this problem ?  

Thanks,

**Comment by bbaia** [comment]
I'll take a look this week

**Comment by bmsoko** [comment]
is there any update with this?

**Comment by bbaia** [comment]
Selenium WebDriver 3.0 have been release, working on it.

**Comment by bbaia** [comment]
Support for Selenium WebDriver 3.0 is available in version 0.9.0
Firefox > v47 still not working

**Comment by iPiyushPatel** [comment]
Thanks @bbaia for update. 
I've tested with Selenium 3.0, Protractor V0.9.1 for IE/Chrome browser and it is working. But as you mentioned still facing issue with Firefox > 47. Any reason why it is breaking on Firefox ?  Do you see any problem related to new Geckodriver ? 

Please advise.

**Comment by bbaia** [comment]
The original project needs to support it first :
http://www.protractortest.org/#/browser-support

**Comment by bbaia** [comment]
Just released v.10 with Firefox support (>v51) !

**Comment by iPiyushPatel** [comment]
Thanks much for update @bbaia .
