### ISSUE TITLE
IgnoreSynchronization is not reflected for "driver.Url = ..."

### ISSUE THREAD

**Issue by gantrior** [bbaia/protractor-net#50]
When testing page which has its parts in Angular and parts in non-Angular, following code is valid in original protractor:
<pre>
browser.ignoreSynchronization = true;
browser.get("/home");
...
browser.ignoreSynchronization = false;
</pre>

which would be simillar to .NET version:
<pre>
var ngDriver = new NgWebDriver(driver);
ngDriver.IgnoreSynchronization = true;
ngDriver.Url = "/home";
...
ngDriver.IgnoreSynchronization = false;
</pre>

however IgnoreSynchronization is ignored in `Url = ".."` which leads to exception. I am not able to test the site when its page is not in Angular, but redirected to Angular page right after the login

**Comment by fjody** [comment]
Hi,
I see this ticket is closed, but is this problem solved?
I hope I didn't create a duplicated bug ticket:
https://github.com/bbaia/protractor-net/issues/84

**Comment by gantrior** [comment]
Yes this bug was fixed already, #84 does not seems to be related.
