### ISSUE TITLE
Not implemented - casting to RemoteWebDriver and RemoteWebElement 

### ISSUE THREAD

**Issue by rakslalsangi** [bbaia/protractor-net#52]
Please implement following items 
1) Casting of NgDriver to RemoteWebDriver 
2) Casting of NgWebElement to RemoteWebElement

**Comment by bbaia** [comment]
1) NgWebDriver wraps an RemoteWebDriver, you can get access to it using the `WrappedDriver` property.
2) Same for NgWebElement, it wraps an RemoteWebElement, you can get access to it using the `WrappedElement` property.
