### ISSUE TITLE
Switching to Development mode

### ISSUE THREAD

**Issue by manchurocas** [bbaia/protractor-net#60]
I am trying to use protractor-net on an Angular 2 site which is also in Production mode, and protractor-net says that "angular is not defined".

Is there a way to switch an app from production mode to development mode when using protractor-net with an Angular 2 app?

I had a similar problem in Angular 1 and ran this command to switch from prod to debug mode:
((OpenQA.Selenium.IJavaScriptExecutor)((IWrapsDriver)instance).WrappedDriver).ExecuteScript("angular.reloadWithDebugInfo();");

**Comment by bbaia** [comment]
So it works in debug mode and fails when using `enableProdMode` ?

**Comment by bbaia** [comment]
> I had a similar problem in Angular 1 and ran this command to switch from prod to debug mode:
((OpenQA.Selenium.IJavaScriptExecutor)((IWrapsDriver)instance).WrappedDriver).ExecuteScript("angular.reloadWithDebugInfo();");

With version 0.9.2, you'll not need to do this

**Comment by manchurocas** [comment]
@bbaia : I thought that was the case, but after some further investigation, that was not the issue.  I was certain it was based on the failures I was seeing, and based on this post in the Protractor GitHub: https://github.com/angular/protractor/issues/3174.  However, it appears I was mistaken.  I apologize for the false alarm.
