### ISSUE TITLE
Custom bootstrapping

### ISSUE THREAD

**Issue by disophisis** [bbaia/protractor-net#62]
We're working with an app that has been updated to make a call to retrieve some data and then continue bootstrapping, so there is a small amount of time where the application may not be bootstrapped.  This is causing issues when waitforangular() is called:

javascript error: [ng:test] http://errors.angularjs.org/1.5.11/ng/test

I'm wondering if there's a way built in to Protractor that would allow us to check to make sure the application is bootstrapped prior to trying to access any elements?

**Comment by bbaia** [comment]
Dis you tried using WebDriverWait from Selenium.wEbDriver.Support package ? 
```csharp
var wait = new WebDriverWait(ngDriver.WrappedDriver, TimeSpan.FromSeconds(15));
wait.Until(ExpectedConditions.UrlToBe("http://myapp.net/home/"));
```

**Comment by disophisis** [comment]
That is an option for sure.  What's happening here is that there's a race condition, it appears.  WaitForAngular() executes a script against the page which calls getTestability(element).  getTestability() throws an error if the app hasn't been bootstrapped.

The best way to attack this would seem to be either at the WaitForAngular() method or lower.  I ended up pulling the code and adding a custom check in WaitForAngular() to make sure the app is bootstrapped before that method can proceed.  I think it is a little expensive though because it uses findelement to check the <body> element for the ng-cloak attribute.  It would be nice if there was some query one could do to determine if the app is bootstrapped.  If there isn't, I can proceed with my custom check.

**Comment by bbaia** [comment]
Can you try using the latest version (0.10) ?

**Comment by disophisis** [comment]
I have updated and tried it; there are quite a few more errors, this one specifically:

javascript error: angular never provided resumeBootstrap

This is application is using angular 1.5.11.

**Comment by bbaia** [comment]
OK, it detects the application is not bootstrapped.
Protractor does not support manual bootstrap [yet](https://github.com/angular/protractor/issues/3857).

Use WebDriverWait for now

**Comment by disophisis** [comment]
Sweet I will keep an eye on this issue you linked.  I think I will also close this for now.

Thanks a lot!
