### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by kedziorm** [bbaia/protractor-net#73]
In the readme file following information is included:

> Supports Microsoft .NET Framework 3.5 and higher.

However, I wonder whether `protractor-net` will be supported in .NET Core or are there any plans for that.

**Comment by bbaia** [comment]
There's a PR on this #72

**Comment by kedziorm** [comment]
Looks great, but will the usage be exactly the same in .NET Core / Visual Studio Code as in old .NET Framework? If I properly checked the PR, the only change in the Readme is added information about support for .NET Core.

**Comment by zeeshankhan0330** [comment]
When can we expect .Net Core supported Library for Protractor?

**Comment by alisterernest** [comment]
Looks like this PR has been in review for quite a while now. When can we expect this to be completed and available?

**Comment by sdjnaik** [comment]
Hi, When can we expect support for .Net Core?

**Comment by bbaia** [comment]
I'll take a look asap!

**Comment by flensrocker** [comment]
Since .Net Core 3 is out and Full .Net Framework is on it's way down to something like EOL, a protractor targeting `netstandard2.0` or similar would be great.

ASP.Net Core 3 will be .Net Core only...

**Comment by bbaia** [comment]
.NET Standard 2.0 is now supported with v0.13
