### ISSUE TITLE
Future plans for protractor-net considering protractor is getting deprecated next year

### ISSUE THREAD

**Issue by rohanade** [bbaia/protractor-net#91]
We have just started using protractor-net in our project and we have another one coming up where we planned to use it.
However, protractor seems to be getting deprecated by 2022 year end (https://github.com/angular/protractor/issues/5502) with Selenum 4 deprecating control flow.

How does this affect the future of protractor-net ?

**Comment by bbaia** [comment]
I already ended development of Protractor for .NET a few years ago but I'm still monitoring this repository to review PRs.
I'm also keeping it up to date by updating dependencies and supporting latest .NET versions.

**Comment by rohanade** [comment]
So there will not be any feature enhancements or bug fixes but the repository will be available for use and maintained to be compatible with newer .NET and selenium versions. Am I correct ?

**Comment by bbaia** [comment]
Yes!

**Comment by rohanade** [comment]
Thanks a lot @bbaia
